name = "skincare-e-commerce"

pages_build_output_dir = "dist"

compatibility_date = "2024-12-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "SESSION"
id = "b7a2c153884a43b6a0341570a8575b3b"
